name: mushaf_mistake_marker
description: "A new Flutter project."

publish_to: 'none' 

version: 2.0.1+7

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  xml: ^6.5.0
  flutter_riverpod: ^2.6.1
  http: ^1.4.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  preload_page_view: ^0.2.0
  collection: ^1.19.1
  shared_preferences: ^2.5.3
  objectbox: ^5.0.1
  objectbox_flutter_libs: ^5.0.1
  objectbox_generator: ^5.0.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/old_madani_pages_data.json
    - assets/sprite_manifests/
    - assets/sprite_sheets_webp/
    - assets/icons/

  fonts:
    - family: ScheherazadeNew
      fonts:
        - asset: fonts/ScheherazadeNew-Regular.ttf
        - asset: fonts/ScheherazadeNew-Medium.ttf
          weight: 500
        - asset: fonts/ScheherazadeNew-SemiBold.ttf
          weight: 600
        - asset: fonts/ScheherazadeNew-Bold.ttf
          weight: 700
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

objectbox:
  output_dir: objectbox

